

const ActionTypes = {

    REGISTER: 'REGISTER',
    REGISTER_SUCCESS: 'REGISTER_SUCCESS',
    REGISTER_FAIL: 'REGISTER_FAIL',

    LOGIN: 'LOGIN',
    LOGIN_SUCCESS: 'LOGIN_SUCCESS',
    ALREADY_LOGGEDIN: 'ALREADY_LOGGEDIN',
    LOGIN_FAIL: 'LOGIN_FAIL',

    SENDEMAIL: 'SENDEMAIL',
    SENDEMAIL_SUCCESS: 'SENDEMAIL_SUCCESS',
    SENDEMAIL_FAIL: 'SENDEMAIL_FAIL',

    LOGOUT: 'LOGOUT',
    LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
    LOGOUT_FAIL: 'LOGOUT_FAIL',

    LOAD_EVERYTHING: 'LOAD_EVERYTHING',
    VideosIsPlay: 'VideosIsPlay',
    NAME: 'NAME',
    AddQuestions: 'ADD_QUESTIONS',

    ONLINEUSERS: 'ONLINEUSERS',
    SCORE: 'SCORE',
    ADD_HISTORY: 'ADD_HISTORY',
    ONLINEUSERS: 'ONLINEUSERS',
    UPDATECHAT: 'UPDATECHAT',
    SELECTEDQUIZDATA: 'SELECTEDQUIZDATA',


    CORRECTANSWERINCR: 'CORRECTANSWERINCR',
    WRONGANSWERINCR: 'WRONGANSWERINCR',
    REINITIALIZEQUIZSTATUS: 'REINITIALIZEQUIZSTATUS',
    UPDATEGAMETYPE: 'UPDATEGAMETYPE',
    INPROGRESSQUIZSTATUS: 'INPROGRESSQUIZSTATUS',

    GETALLUSERS: 'GETALLUSERS',
    GETCIRCLEMEMBERS: 'GETCIRCLEMEMBERS',

    RECORDTIME: 'RECORDTIME',
    REINITIALIZESCORE: 'REINITIALIZESCORE',
    SETNUMBEROFOPPONENT: 'SETNUMBEROFOPPONENT',

    INITBFMUSIC: 'INITBFMUSIC',
    INITCORRECTMUSIC: 'INITCORRECTMUSIC',
    INITWRONGTMUSIC: 'INITWRONGTMUSIC',

    MUSICFALSE: 'MUSICFALSE',
    SOUNDEFFECTFALSE: 'SOUNDEFFECTFALSE',

    CONNECTIONSTATUS: 'CONNECTIONSTATUS',
    CURRENTUSER: 'CURRENTUSER',

    USERLOGGEDIN: 'USERLOGGEDIN'

}

export default ActionTypes;